---
title: "p8105_hw2_jsg2145"
author: "Jared Garfinkel"
date: "9/27/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## Homework 2

### Problem 1

```{r}
mr_trash = readxl::read_excel("./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", 
                              sheet = "Mr. Trash Wheel", 
                              range = readxl::cell_cols("A:N")) %>% 
  janitor::clean_names() %>% 
  filter(!is.na(dumpster)) %>% 
  mutate(
    sports_balls = 
      round(sports_balls, digits = 0) %>% 
      as.integer())
```

```{r}
precip_18 = readxl::read_excel("./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx",
                              sheet = "2018 Precipitation", range = readxl::cell_rows(2:14)) %>% 
  janitor::clean_names() %>% 
  filter(!is.na(total)) %>% 
  mutate(year = 2018)

precip_17 = readxl::read_excel("./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx",
                               sheet = "2017 Precipitation", range = readxl::cell_rows(2:14)) %>% 
  janitor::clean_names() %>% 
  filter(!is.na(total)) %>% 
  mutate(year = 2017)
```

